// playground/react-app/src/components/Card.tsx
import React from 'react'

export interface CardProps {
  title?: string
  children: React.ReactNode
  className?: string
}

export function Card({ title, children, className = '' }: CardProps) {
  return (
    <div className={`card ${className}`}>
      {title && <div className="card-header">{title}</div>}
      <div className="card-body">
        {children}
      </div>
    </div>
  )
}

// playground/solid-app/src/components/Card.tsx
import type { Component, JSX } from 'solid-js'

export interface CardProps {
  title?: string
  children: JSX.Element
  class?: string
}

export const Card: Component<CardProps> = (props) => {
  return (
    <div class={`card ${props.class || ''}`}>
      {props.title && <div class="card-header">{props.title}</div>}
      <div class="card-body">
        {props.children}
      </div>
    </div>
  )
}
